# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtunnel < Formula
  desc ""
  homepage "https://github.com/manoj-inukolunu/homebrew-formulae"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.4/jtunnel-go_Darwin_arm64.tar.gz"
      sha256 "038fca4b6512078dea8d9f2e8cbbe38134f600fa8cec03dffb8c464b14f87b7d"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.4/jtunnel-go_Darwin_x86_64.tar.gz"
      sha256 "b7fb109ddba4746659c78f2691ac61e77343cc0542c80d3f2d87b444503c7208"

      def install
        bin.install "jtunnel-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.4/jtunnel-go_Linux_arm64.tar.gz"
      sha256 "98b53c1cb3635b2810917a00c92b86e954afc551fc968436bc6f402f60969443"

      def install
        bin.install "jtunnel-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manoj-inukolunu/jtunnel-go/releases/download/v0.0.4/jtunnel-go_Linux_x86_64.tar.gz"
      sha256 "a0869f1f748201cdddbbb5e3e4bac1c1c4a09b215dcff402e918ec1a40bb9ca2"

      def install
        bin.install "jtunnel-go"
      end
    end
  end
end
